import { Recipe, Step, Ingredient } from './api';

const makeIngredients = (items: { name: string; name_zh: string; amount: string }[]): Ingredient[] => items;

const makeSteps = (items: { order: number; description: string; description_zh: string; image?: string }[]): Step[] => items;

export const MOCK_RECIPES: Recipe[] = [
  {
    id: '1',
    title: 'Kung Pao Chicken',
    title_zh: '宫保鸡丁',
    description:
      'A spicy, stir-fried Chinese dish made with cubed chicken, peanuts, vegetables, and chili peppers. A Sichuan classic loved worldwide.',
    description_zh:
      '宫保鸡丁是四川传统名菜，以嫩鸡丁、花生米、辣椒爆炒而成，口感麻辣鲜香，深受全球食客喜爱。',
    cover_image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=800&q=80',
    category: 'Sichuan',
    difficulty: 'medium',
    cook_time: 15,
    prep_time: 20,
    servings: 2,
    likes_count: 342,
    avg_rating: 4.7,
    ratings_count: 128,
    comments_count: 32,
    favorites_count: 45,
    is_published: true,
    created_at: '2024-01-10T08:00:00Z',
    tags: [
      { id: 'mock-spicy', label: 'Spicy', label_zh: '辣味' },
      { id: 'mock-stirfry', label: 'Stir-fry', label_zh: '爆炒' },
    ],
    ingredients: makeIngredients([
      { name: 'Chicken breast', name_zh: '鸡胸肉', amount: '300g' },
      { name: 'Peanuts', name_zh: '花生米', amount: '80g' },
      { name: 'Dried chili peppers', name_zh: '干辣椒', amount: '8 pcs' },
      { name: 'Scallions', name_zh: '大葱', amount: '2 stalks' },
      { name: 'Garlic', name_zh: '大蒜', amount: '4 cloves' },
      { name: 'Ginger', name_zh: '生姜', amount: '1 thumb' },
      { name: 'Soy sauce', name_zh: '生抽', amount: '2 tbsp' },
      { name: 'Rice vinegar', name_zh: '米醋', amount: '1 tbsp' },
      { name: 'Sugar', name_zh: '白糖', amount: '1 tsp' },
      { name: 'Cornstarch', name_zh: '淀粉', amount: '1 tbsp' },
    ]),
    steps: makeSteps([
      {
        order: 1,
        description: 'Cut chicken into 1.5 cm cubes. Marinate with soy sauce, cornstarch, and a pinch of salt for 15 minutes.',
        description_zh: '鸡胸肉切成约1.5厘米的小丁，加入生抽、淀粉和少许盐腌制15分钟。',
        image: 'https://images.unsplash.com/photo-1604908177453-7462950a6a3b?w=600&q=80',
      },
      {
        order: 2,
        description: 'Mix sauce: soy sauce, vinegar, sugar, cornstarch, and a splash of water in a small bowl.',
        description_zh: '调制酱汁：将生抽、米醋、白糖、淀粉和少量清水在小碗中混合均匀备用。',
        image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80',
      },
      {
        order: 3,
        description: 'Heat oil in wok over high heat. Stir-fry dried chilies and Sichuan peppercorns until fragrant (30 sec).',
        description_zh: '热锅热油，大火将干辣椒和花椒爆炒约30秒至出香味。',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80',
      },
      {
        order: 4,
        description: 'Add chicken, stir-fry until golden. Add garlic and ginger. Pour in sauce, toss in peanuts, and serve.',
        description_zh: '下鸡丁翻炒至金黄，加入蒜末和姜末，倒入酱汁，最后放入花生米翻炒均匀即可出锅。',
        image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&q=80',
      },
    ]),
  },
  {
    id: '2',
    title: 'Red Braised Pork Belly',
    title_zh: '红烧肉',
    description:
      'Melt-in-your-mouth pork belly braised in soy sauce, Shaoxing wine, and rock sugar. A Chinese comfort food icon.',
    description_zh:
      '红烧肉是中国最具代表性的家常菜之一，五花肉经过慢火炖煮，色泽红亮，肥而不腻，入口即化。',
    cover_image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&q=80',
    category: 'Braised',
    difficulty: 'medium',
    cook_time: 90,
    prep_time: 15,
    servings: 4,
    likes_count: 521,
    avg_rating: 4.9,
    ratings_count: 234,
    comments_count: 58,
    favorites_count: 89,
    is_published: true,
    created_at: '2024-01-12T08:00:00Z',
    tags: [
      { id: 'mock-comfort', label: 'Comfort Food', label_zh: '家常' },
      { id: 'mock-braised', label: 'Braised', label_zh: '红烧' },
    ],
    ingredients: makeIngredients([
      { name: 'Pork belly', name_zh: '五花肉', amount: '600g' },
      { name: 'Shaoxing wine', name_zh: '绍兴黄酒', amount: '4 tbsp' },
      { name: 'Dark soy sauce', name_zh: '老抽', amount: '2 tbsp' },
      { name: 'Light soy sauce', name_zh: '生抽', amount: '3 tbsp' },
      { name: 'Rock sugar', name_zh: '冰糖', amount: '30g' },
      { name: 'Star anise', name_zh: '八角', amount: '2 pcs' },
      { name: 'Cinnamon stick', name_zh: '桂皮', amount: '1 piece' },
      { name: 'Ginger', name_zh: '生姜', amount: '5 slices' },
      { name: 'Scallions', name_zh: '大葱', amount: '2 stalks' },
    ]),
    steps: makeSteps([
      {
        order: 1,
        description: 'Blanch pork belly in boiling water for 5 minutes. Remove and cut into 3cm cubes.',
        description_zh: '五花肉冷水下锅焯水5分钟，捞出洗净，切成约3厘米的方块。',
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
      },
      {
        order: 2,
        description: 'Melt rock sugar in oil until amber. Add pork and stir-fry until coated in caramel.',
        description_zh: '锅中热油，将冰糖炒化至琥珀色，放入五花肉翻炒至表面均匀裹上糖色。',
        image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?w=600&q=80',
      },
      {
        order: 3,
        description: 'Add Shaoxing wine, soy sauces, star anise, cinnamon, ginger, scallions, and enough water to cover.',
        description_zh: '加入绍兴黄酒、老抽、生抽、八角、桂皮、姜片、葱段，加水至刚好没过肉块。',
        image: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&q=80',
      },
      {
        order: 4,
        description: 'Bring to boil, then simmer on low heat for 60–75 minutes. Increase heat to reduce sauce until glossy.',
        description_zh: '大火烧开后转小火慢炖60-75分钟，最后开大火收汁至浓稠发亮即可。',
        image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&q=80',
      },
    ]),
  },
  {
    id: '3',
    title: 'Mapo Tofu',
    title_zh: '麻婆豆腐',
    description:
      'Silky tofu in a fiery, numbing sauce made with doubanjiang, ground pork, and Sichuan peppercorns. Bold and unforgettable.',
    description_zh:
      '麻婆豆腐是四川经典名菜，嫩豆腐搭配豆瓣酱、猪肉末和花椒，麻辣鲜烫，风味十足。',
    cover_image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
    category: 'Sichuan',
    difficulty: 'easy',
    cook_time: 20,
    prep_time: 10,
    servings: 2,
    likes_count: 287,
    avg_rating: 4.6,
    ratings_count: 99,
    comments_count: 21,
    favorites_count: 34,
    is_published: true,
    created_at: '2024-01-15T08:00:00Z',
    tags: [
      { id: 'mock-spicy', label: 'Spicy', label_zh: '辣味' },
      { id: 'mock-tofu', label: 'Tofu', label_zh: '豆腐' },
      { id: 'mock-quick', label: 'Quick', label_zh: '快手' },
    ],
    ingredients: makeIngredients([
      { name: 'Soft tofu', name_zh: '嫩豆腐', amount: '400g' },
      { name: 'Ground pork', name_zh: '猪肉末', amount: '100g' },
      { name: 'Doubanjiang (spicy bean paste)', name_zh: '郫县豆瓣酱', amount: '2 tbsp' },
      { name: 'Sichuan peppercorns (ground)', name_zh: '花椒粉', amount: '1 tsp' },
      { name: 'Garlic', name_zh: '大蒜', amount: '4 cloves' },
      { name: 'Ginger', name_zh: '生姜', amount: '1 thumb' },
      { name: 'Chicken stock', name_zh: '鸡汤', amount: '200ml' },
      { name: 'Cornstarch', name_zh: '淀粉', amount: '1 tbsp' },
      { name: 'Scallions', name_zh: '小葱', amount: '2 stalks' },
    ]),
    steps: makeSteps([
      {
        order: 1,
        description: 'Cut tofu into 2cm cubes and gently blanch in salted boiling water for 2 minutes. Drain carefully.',
        description_zh: '豆腐切成约2厘米的方块，在加盐的沸水中轻煮2分钟，捞出沥干备用。',
        image: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=600&q=80',
      },
      {
        order: 2,
        description: 'Stir-fry ground pork until cooked. Add doubanjiang, garlic, ginger and fry until oil turns red.',
        description_zh: '锅中炒熟猪肉末，加入豆瓣酱、蒜末和姜末翻炒，至油色变红出香味。',
        image: 'https://images.unsplash.com/photo-1540914124281-342587941389?w=600&q=80',
      },
      {
        order: 3,
        description: 'Add stock, then gently slide in tofu. Simmer 5 minutes. Thicken with cornstarch slurry.',
        description_zh: '加入鸡汤，轻轻放入豆腐，小火炖煮5分钟，用水淀粉勾芡收汁。',
        image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80',
      },
      {
        order: 4,
        description: 'Finish with Sichuan peppercorn powder and chopped scallions. Serve immediately over rice.',
        description_zh: '最后撒上花椒粉和葱花，趁热配米饭食用。',
        image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80',
      },
    ]),
  },
  {
    id: '4',
    title: 'Zha Jiang Mian',
    title_zh: '炸酱面',
    description:
      'Beijing-style noodles topped with a rich, savory pork and fermented soybean paste sauce, garnished with fresh vegetables.',
    description_zh:
      '炸酱面是北京最具代表性的家常面食，浓郁的猪肉炸酱配上爽滑面条和新鲜时蔬，简单美味。',
    cover_image: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&q=80',
    category: 'Noodles',
    difficulty: 'easy',
    cook_time: 25,
    prep_time: 15,
    servings: 2,
    likes_count: 198,
    avg_rating: 4.5,
    ratings_count: 76,
    comments_count: 18,
    favorites_count: 27,
    is_published: true,
    created_at: '2024-01-18T08:00:00Z',
    tags: [
      { id: 'mock-noodles', label: 'Noodles', label_zh: '面食' },
      { id: 'mock-quick', label: 'Quick', label_zh: '快手' },
    ],
    ingredients: makeIngredients([
      { name: 'Fresh thick noodles', name_zh: '新鲜粗面条', amount: '300g' },
      { name: 'Ground pork', name_zh: '猪肉末', amount: '200g' },
      { name: 'Yellow soybean paste (tianmian sauce)', name_zh: '甜面酱', amount: '3 tbsp' },
      { name: 'Fermented black bean paste', name_zh: '黄酱', amount: '2 tbsp' },
      { name: 'Shaoxing wine', name_zh: '绍兴黄酒', amount: '1 tbsp' },
      { name: 'Cucumber', name_zh: '黄瓜', amount: '1/2 pcs' },
      { name: 'Radish', name_zh: '心里美萝卜', amount: '1/4 pcs' },
      { name: 'Scallions', name_zh: '大葱', amount: '2 stalks' },
      { name: 'Edamame', name_zh: '毛豆', amount: '50g' },
    ]),
    steps: makeSteps([
      {
        order: 1,
        description: 'Prepare toppings: julienne cucumber and radish, slice scallions, boil edamame.',
        description_zh: '备菜：黄瓜和萝卜切丝，大葱切段，毛豆煮熟备用。',
        image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80',
      },
      {
        order: 2,
        description: 'Stir-fry ground pork until cooked. Mix in tianmian sauce and black bean paste. Add Shaoxing wine and simmer 8 min.',
        description_zh: '猪肉末炒熟后，加入甜面酱和黄酱翻炒均匀，加入绍兴黄酒，小火慢炒8分钟至酱香浓郁。',
        image: 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=600&q=80',
      },
      {
        order: 3,
        description: 'Cook noodles in boiling water until al dente. Rinse under cold water, drain well.',
        description_zh: '面条在沸水中煮至刚好熟透（有嚼劲），捞出过冷水，沥干备用。',
        image: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&q=80',
      },
      {
        order: 4,
        description: 'Place noodles in a bowl, spoon fried sauce on top. Arrange fresh toppings around and mix before eating.',
        description_zh: '将面条盛入碗中，在中间放上炸酱，四周摆上各种配菜，食用前拌匀即可。',
        image: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&q=80',
      },
    ]),
  },
  {
    id: '5',
    title: 'Soup Dumplings',
    title_zh: '小笼包',
    description:
      "Shanghai's iconic steamed dumplings filled with seasoned pork and a rich, gelatinous broth that melts into soup when steamed.",
    description_zh:
      '小笼包是上海传统点心，薄皮鲜肉，内含鲜美汤汁，蒸熟后一口咬下汤汁四溢，鲜美无比。',
    cover_image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&q=80',
    category: 'Dim Sum',
    difficulty: 'hard',
    cook_time: 20,
    prep_time: 60,
    servings: 4,
    likes_count: 456,
    avg_rating: 4.8,
    ratings_count: 187,
    comments_count: 44,
    favorites_count: 67,
    is_published: true,
    created_at: '2024-01-20T08:00:00Z',
    tags: [
      { id: 'mock-dimsum', label: 'Dim Sum', label_zh: '点心' },
      { id: 'mock-dumplings', label: 'Dumplings', label_zh: '饺子' },
    ],
    ingredients: makeIngredients([
      { name: 'All-purpose flour', name_zh: '中筋面粉', amount: '250g' },
      { name: 'Boiling water', name_zh: '沸水', amount: '130ml' },
      { name: 'Ground pork (fatty)', name_zh: '肥瘦猪肉末', amount: '300g' },
      { name: 'Aspic jelly (pork gelatin)', name_zh: '皮冻', amount: '100g' },
      { name: 'Soy sauce', name_zh: '生抽', amount: '2 tbsp' },
      { name: 'Sesame oil', name_zh: '香油', amount: '1 tbsp' },
      { name: 'Ginger', name_zh: '生姜', amount: '15g' },
      { name: 'Shaoxing wine', name_zh: '绍兴黄酒', amount: '1 tbsp' },
      { name: 'Sugar', name_zh: '白糖', amount: '1 tsp' },
      { name: 'Black vinegar', name_zh: '镇江香醋', amount: 'for dipping' },
    ]),
    steps: makeSteps([
      {
        order: 1,
        description: 'Make dough: pour boiling water into flour gradually, mix into a soft dough. Cover and rest 30 min.',
        description_zh: '和面：将沸水缓缓倒入面粉中，边倒边搅拌，揉成光滑的软面团，盖好醒面30分钟。',
        image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&q=80',
      },
      {
        order: 2,
        description: 'Mix filling: combine pork, diced aspic, soy sauce, sesame oil, ginger, wine, and sugar. Stir in one direction until sticky.',
        description_zh: '调制馅料：将猪肉末、切碎的皮冻、生抽、香油、姜末、黄酒和白糖混合，朝一个方向搅拌至上劲。',
        image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&q=80',
      },
      {
        order: 3,
        description: 'Roll dough into thin wrappers (~8cm diameter). Place filling in center, pleat and seal the top with 18 folds.',
        description_zh: '面团擀成约8厘米直径的薄皮，包入馅料，用双手捏出18个褶子，将顶部收口封好。',
        image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&q=80',
      },
      {
        order: 4,
        description: 'Steam over high heat for 8–10 minutes. Serve immediately with ginger strips and black vinegar.',
        description_zh: '放入蒸笼，大火蒸8-10分钟。立即上桌，搭配姜丝和镇江香醋食用。',
        image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&q=80',
      },
    ]),
  },
];

export const MOCK_COMMENTS = [
  {
    id: 'c1',
    user_id: 'u1',
    recipe_id: '1',
    content: 'Amazing recipe! The peanuts add such great texture. I added extra chili for more heat.',
    rating: 5,
    created_at: '2024-02-01T10:00:00Z',
    user: { name: 'Sarah K.', avatar_url: 'https://i.pravatar.cc/50?img=1' },
  },
  {
    id: 'c2',
    user_id: 'u2',
    recipe_id: '1',
    content: 'Perfectly balanced flavors! My family loved it.',
    rating: 4,
    created_at: '2024-02-03T14:00:00Z',
    user: { name: 'Mike T.', avatar_url: 'https://i.pravatar.cc/50?img=2' },
  },
  {
    id: 'c3',
    user_id: 'u3',
    recipe_id: '2',
    content: 'This red braised pork is absolutely melt-in-your-mouth delicious!',
    rating: 5,
    created_at: '2024-02-05T09:00:00Z',
    user: { name: 'Emma L.', avatar_url: 'https://i.pravatar.cc/50?img=3' },
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All', label_zh: '全部' },
  { id: 'Sichuan', label: 'Sichuan', label_zh: '四川' },
  { id: 'Braised', label: 'Braised', label_zh: '炖菜' },
  { id: 'Noodles', label: 'Noodles', label_zh: '面食' },
  { id: 'Dim Sum', label: 'Dim Sum', label_zh: '点心' },
  { id: 'Cantonese', label: 'Cantonese', label_zh: '粤菜' },
  { id: 'Hunan', label: 'Hunan', label_zh: '湘菜' },
];

export const DIFFICULTIES = [
  { id: 'all', label: 'All', label_zh: '全部' },
  { id: 'easy', label: 'Easy', label_zh: '简单' },
  { id: 'medium', label: 'Medium', label_zh: '中等' },
  { id: 'hard', label: 'Hard', label_zh: '困难' },
];
